spring:
  application:
    name: requirements-management-backend

  jpa:
    properties:
      hibernate.jdbc.time_zone: America/Lima

  jackson:
    time-zone: America/Lima
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT}

app:
  errors:
    include-debug-info: false
