spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION_KEY}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
    session-days: ${JWT_SESSION_DAYS}

app:
  errors:
    include-debug-info: true
